"""initial_migration

Revision ID: 1b52ee60ee3d
Revises:
Create Date: 2025-07-20 12:54:52.560792
Update Date: 2026-01-02 13:56:43.153857
"""

from alembic import op
import sqlalchemy as sa


revision: str = "1b52ee60ee3d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sites",
        sa.Column("tag", sa.String(length=32), nullable=False),
        sa.Column("admin_email", sa.String(length=255), nullable=False),
        sa.Column("admin_password", sa.String(length=72), nullable=False),
        sa.Column("site_type", sa.String(length=30), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("installed_at", sa.DateTime(), nullable=True),
        sa.Column("removal_reason", sa.String(length=255), nullable=True),
        sa.Column("removed_at", sa.DateTime(), nullable=True),
        sa.Column("removed_ip", sa.String(length=45), nullable=True),
        sa.Column("created_ip", sa.String(length=45), nullable=True),
        sa.Column("last_login_ip", sa.String(length=45), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("donated_amount", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("tag"),
        sa.UniqueConstraint("tag"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sites")
    # ### end Alembic commands ###
