"""donated_amount_default

Revision ID: 2af8d64b9b12
Revises: 3e8ca0fd3607
Create Date: 2026-02-11 18:12:32.027724
"""

from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "2af8d64b9b12"
down_revision = "3e8ca0fd3607"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("UPDATE sites SET donated_amount = 0.0 WHERE donated_amount IS NULL")
    op.alter_column(
        "sites",
        "donated_amount",
        existing_type=mysql.FLOAT(),
        server_default="0",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sites",
        "donated_amount",
        existing_type=mysql.FLOAT(),
        default=None,
        nullable=True,
    )
    # ### end Alembic commands ###
