"""nullable_installed_at

Revision ID: 3e8ca0fd3607
Revises: acec4611506e
Create Date: 2026-02-09 20:55:52.355600
"""

from alembic import op
from sqlalchemy.dialects import mysql

revision: str = '3e8ca0fd3607'
down_revision = 'acec4611506e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'installed_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'installed_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
