"""adjust_site_schema_types

Revision ID: acec4611506e
Revises: 1b52ee60ee3d
Create Date: 2026-02-09 16:42:41.233378
"""

from alembic import op
import sqlalchemy as sa


revision: str = 'acec4611506e'
down_revision = '1b52ee60ee3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'hostname',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('sites', 'installed_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'installed_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('sites', 'hostname',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
